//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDB_SZFPZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KontaktKompanije
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KontaktKompanije()
        {
            this.SharingIsCarings = new HashSet<SharingIsCaring>();
            this.Suradnjas = new HashSet<Suradnja>();
            this.Uploaded_File = new HashSet<Uploaded_File>();
        }
    
        public int IDKontakt { get; set; }
        public string ImeKontakt { get; set; }
        public string PrezimeKontakt { get; set; }
        public string EmailKontakt { get; set; }
        public string TelefonKontakt { get; set; }
        public string MobitelKontakt { get; set; }
        public string FunkcijaUKompaniji { get; set; }
        public string OpisKontakta { get; set; }
        public bool ZaposlenValidan { get; set; }
        public int IDKompanijaKontakta { get; set; }
        public string ImePrezimeKontakta { get; set; }
    
        public virtual Kompanija Kompanija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SharingIsCaring> SharingIsCarings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Suradnja> Suradnjas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uploaded_File> Uploaded_File { get; set; }
    }
}
