//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDB_SZFPZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projekt()
        {
            this.Suradnjas = new HashSet<Suradnja>();
            this.Uploaded_File = new HashSet<Uploaded_File>();
            this.Zadatak_Projekta = new HashSet<Zadatak_Projekta>();
        }
    
        public int IDProjekt { get; set; }
        public string NazivProjekt { get; set; }
        public string OpisProjekt { get; set; }
        public string WebAdresaProjekta { get; set; }
        public Nullable<System.DateTime> GodinaProjekt { get; set; }
        public Nullable<int> CiljFRFinancije { get; set; }
        public string CiljFRMaterijali { get; set; }
        public int StatusProjekta { get; set; }
        public int PrioritetProjekta { get; set; }
    
        public virtual PrioritetProjekta PrioritetProjekta1 { get; set; }
        public virtual StatusProjekta StatusProjekta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Suradnja> Suradnjas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uploaded_File> Uploaded_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zadatak_Projekta> Zadatak_Projekta { get; set; }
    }
}
