//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDB_SZFPZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharingIsCaring
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SharingIsCaring()
        {
            this.Uploaded_File = new HashSet<Uploaded_File>();
        }
    
        public int IDSiC { get; set; }
        public Nullable<System.DateTime> DatumIzmjene { get; set; }
        public string PrimjerDopisa { get; set; }
        public string OsobniKomentarDopisa { get; set; }
        public int OdgClan { get; set; }
        public Nullable<int> KontaktKompanije { get; set; }
        public Nullable<int> IDKompanija { get; set; }
        public Nullable<int> VrstaDopisa { get; set; }
    
        public virtual ClanFROdbora ClanFROdbora { get; set; }
        public virtual Kompanija Kompanija { get; set; }
        public virtual KontaktKompanije KontaktKompanije1 { get; set; }
        public virtual TipSuradnje TipSuradnje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uploaded_File> Uploaded_File { get; set; }
    }
}
