//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDB_SZFPZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suradnja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suradnja()
        {
            this.Uploaded_File = new HashSet<Uploaded_File>();
        }
    
        public int IDSuradnja { get; set; }
        public string KomentarSuradnja { get; set; }
        public int OdgovoranClan { get; set; }
        public Nullable<int> TipSuradnja { get; set; }
        public Nullable<int> StatusSuradnja { get; set; }
        public Nullable<int> KontaktKompanije { get; set; }
        public int IDProjekt { get; set; }
        public int IDKompanija { get; set; }
        public System.DateTime DatumZadnjegKontakta { get; set; }
        public Nullable<int> FinancijskaVrijednost { get; set; }
        public string MaterijalnaVrijednost { get; set; }
    
        public virtual ClanFROdbora ClanFROdbora { get; set; }
        public virtual Kompanija Kompanija { get; set; }
        public virtual KontaktKompanije KontaktKompanije1 { get; set; }
        public virtual Projekt Projekt { get; set; }
        public virtual StatusSuradnja StatusSuradnja1 { get; set; }
        public virtual TipSuradnje TipSuradnje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uploaded_File> Uploaded_File { get; set; }
    }
}
