//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDB_SZFPZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zadatak_Projekta
    {
        public int ID_Zadatak { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public int Status { get; set; }
        public Nullable<int> Projekt { get; set; }
    
        public virtual Projekt Projekt1 { get; set; }
        public virtual Status_Zadatka Status_Zadatka { get; set; }
    }
}
